services:
  # --- PostgreSQL Database ---
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # --- Django Backend ---
  backend:
    build:
      context: ./services/cms-backend
      dockerfile: Dockerfile
    container_name: django_backend
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn cms_api.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./services/cms-backend:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY:-changeme}
      - DJANGO_ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-app_db}
    depends_on:
      - db
    ports:
      - "8000:8000"

  # --- React Frontend ---
  frontend:
    build:
      context: ./services/cms-frontend
      dockerfile: Dockerfile
    container_name: frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./services/cms-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
