# Generated by Django 5.1.4 on 2025-10-07 20:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_incident', models.DateField(blank=True, null=True)),
                ('product_or_service', models.CharField(max_length=255)),
                ('order_or_invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='complaints/supporting_docs/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_involved', models.CharField(blank=True, max_length=255, null=True)),
                ('actions_already_taken', models.TextField(blank=True, null=True)),
                ('desired_outcome', models.TextField(blank=True, max_length=255, null=True)),
                ('complaint_channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('PHONE', 'Phone'), ('IN_PERSON', 'In Person'), ('WEB', 'Website'), ('SOCIAL_MEDIA', 'Social Media')], default='WEB', max_length=50, null=True)),
                ('complaint_status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('draft', 'Draft'), ('validated', 'Validated'), ('delivered', 'Delivered')], default='RECEIVED', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Complaint',
                'verbose_name_plural': 'Customer Complaints',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution_text', models.TextField()),
                ('resolved_by', models.CharField(max_length=100)),
                ('validated_by_ai', models.BooleanField(default=False)),
                ('solution_status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('draft', 'Draft'), ('validated', 'Validated'), ('delivered', 'Delivered')], default='RECEIVED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='submission.complaint')),
            ],
        ),
    ]
