# Generated by Django 5.1.4 on 2025-10-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('PHONE', 'Phone'), ('IN_PERSON', 'In Person'), ('WEB', 'Website'), ('SOCIAL_MEDIA', 'Social Media')], default='WEB', max_length=50, null=True),
        ),
    ]
